[pytest]

markers =

    smoke

addopts =

    -sv
# Перезапускает тест, если возник таймаут
#    --only-rerun TimeoutException
# Перезапускает тест, при ошибках соединения
#    --only-rerun HTTPSConnectionPool
# Перезапускает тест, если элемент стал устаревшим
#    --only-rerun StateElementReferenceException
# Перезапускает тест, если сессия браузера или драйвера неожиданно завершилась
#    --only-rerun InvalidSessionIdException